default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: anirudh
  host: localhost
  pool: 5

development:
  <<: *default
  database: circuitverse_development

test:
  <<: *default
  database: circuitverse_test

production:
  <<: *default
  database: circuitverse_production
  username: postgres
  password: <%= ENV['CIRCUITVERSE_DATABASE_PASSWORD'] %>
