default: &default
  adapter: postgresql
  encoding: unicode
  username: anirudh
  password: yourpassword
  host: localhost
  pool: 5

development:
  <<: *default
  database: circuitverse_development

test:
  <<: *default
  database: circuitverse_test
