name: Qlty Checks

on:
  pull_request:
    branches:
      - main

jobs:
  qlty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run qlty check
        run: npx qlty check

      - name: Run qlty fmt
        run: npx qlty fmt --check

      - name: Run qlty coverage
        run: npx qlty coverage
